# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AlienWare/Course/ECE532/MileStone7/IPs/FPGA_ADC/ip_repo/ADC_fpga_d_1/src/pixel_buffer/pixel_buffer.xci
# IP: The module: 'pixel_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AlienWare/Course/ECE532/MileStone7/IPs/FPGA_ADC/ip_repo/ADC_fpga_d_1/src/pixel_buffer/pixel_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixel_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/IPs/FPGA_ADC/ip_repo/ADC_fpga_d_1/src/pixel_buffer/pixel_buffer.xci
# IP: The module: 'pixel_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AlienWare/Course/ECE532/MileStone7/IPs/FPGA_ADC/ip_repo/ADC_fpga_d_1/src/pixel_buffer/pixel_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixel_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
