-- Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity hdmi_wrapper is
  Port ( 
    DC : out STD_LOGIC;
    DDC_scl_io : inout STD_LOGIC;
    DDC_sda_io : inout STD_LOGIC;
    DDR3_addr : out STD_LOGIC_VECTOR ( 14 downto 0 );
    DDR3_ba : out STD_LOGIC_VECTOR ( 2 downto 0 );
    DDR3_cas_n : out STD_LOGIC;
    DDR3_ck_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    DDR3_ck_p : out STD_LOGIC_VECTOR ( 0 to 0 );
    DDR3_cke : out STD_LOGIC_VECTOR ( 0 to 0 );
    DDR3_dm : out STD_LOGIC_VECTOR ( 1 downto 0 );
    DDR3_dq : inout STD_LOGIC_VECTOR ( 15 downto 0 );
    DDR3_dqs_n : inout STD_LOGIC_VECTOR ( 1 downto 0 );
    DDR3_dqs_p : inout STD_LOGIC_VECTOR ( 1 downto 0 );
    DDR3_odt : out STD_LOGIC_VECTOR ( 0 to 0 );
    DDR3_ras_n : out STD_LOGIC;
    DDR3_reset_n : out STD_LOGIC;
    DDR3_we_n : out STD_LOGIC;
    GPIO_0_tri_o : out STD_LOGIC_VECTOR ( 7 downto 0 );
    IV : out STD_LOGIC;
    RES : out STD_LOGIC;
    SCLK : out STD_LOGIC;
    SDIN : out STD_LOGIC;
    TMDS_IN_clk_n : in STD_LOGIC;
    TMDS_IN_clk_p : in STD_LOGIC;
    TMDS_IN_data_n : in STD_LOGIC_VECTOR ( 2 downto 0 );
    TMDS_IN_data_p : in STD_LOGIC_VECTOR ( 2 downto 0 );
    TMDS_OUT_clk_n : out STD_LOGIC;
    TMDS_OUT_clk_p : out STD_LOGIC;
    TMDS_OUT_data_n : out STD_LOGIC_VECTOR ( 2 downto 0 );
    TMDS_OUT_data_p : out STD_LOGIC_VECTOR ( 2 downto 0 );
    VBAT : out STD_LOGIC;
    VDD : out STD_LOGIC;
    b0_ch : out STD_LOGIC;
    b1_ch : out STD_LOGIC;
    b2_ch : out STD_LOGIC;
    b3_ch : out STD_LOGIC;
    clk_d : out STD_LOGIC;
    clk_dac : out STD_LOGIC;
    clk_dac_d : out STD_LOGIC;
    clk_dac_p : out STD_LOGIC;
    clk_p : out STD_LOGIC;
    clk_short : out STD_LOGIC;
    clock_on_off : out STD_LOGIC;
    cs_b0 : out STD_LOGIC;
    cs_b1 : out STD_LOGIC;
    cs_b2 : out STD_LOGIC;
    d : in STD_LOGIC_VECTOR ( 7 downto 0 );
    dac_stim_0 : out STD_LOGIC;
    dac_stim_1 : out STD_LOGIC;
    dac_stim_2 : out STD_LOGIC;
    dac_stim_3 : out STD_LOGIC;
    dd0 : out STD_LOGIC;
    dd1 : out STD_LOGIC;
    dd2 : out STD_LOGIC;
    dd3 : out STD_LOGIC;
    df_set : out STD_LOGIC;
    en : out STD_LOGIC;
    en_v : out STD_LOGIC;
    eth_int_b : in STD_LOGIC;
    eth_mdc : out STD_LOGIC;
    eth_mdio : inout STD_LOGIC;
    eth_pme_b : in STD_LOGIC;
    eth_rst_b : out STD_LOGIC;
    eth_rxck : in STD_LOGIC;
    eth_rxctl : in STD_LOGIC;
    eth_rxd : in STD_LOGIC_VECTOR ( 3 downto 0 );
    eth_txck : out STD_LOGIC;
    eth_txctl : out STD_LOGIC;
    eth_txd : out STD_LOGIC_VECTOR ( 3 downto 0 );
    hdmi_hpd : out STD_LOGIC_VECTOR ( 0 to 0 );
    hdmi_rx_txen : out STD_LOGIC_VECTOR ( 0 to 0 );
    i_dac_en : out STD_LOGIC;
    in_sample : out STD_LOGIC;
    pad_a_sel1 : out STD_LOGIC;
    pad_a_sel2 : out STD_LOGIC;
    pad_a_sel3 : out STD_LOGIC;
    pad_a_sel4 : out STD_LOGIC;
    pad_a_sel5 : out STD_LOGIC;
    pad_a_sel6 : out STD_LOGIC;
    pad_b_sel1 : out STD_LOGIC;
    pad_b_sel2 : out STD_LOGIC;
    pad_b_sel3 : out STD_LOGIC;
    pad_b_sel4 : out STD_LOGIC;
    reset : in STD_LOGIC;
    reswww : in STD_LOGIC;
    rst_b : out STD_LOGIC;
    s0 : out STD_LOGIC;
    s1 : out STD_LOGIC;
    s2 : out STD_LOGIC;
    s3 : out STD_LOGIC;
    s4 : out STD_LOGIC;
    s5 : out STD_LOGIC;
    sample_c : out STD_LOGIC;
    sample_tr : out STD_LOGIC;
    start_sending_0 : out STD_LOGIC;
    sys_clk_i : in STD_LOGIC;
    tr_b0 : out STD_LOGIC;
    tr_b1 : out STD_LOGIC;
    tr_data_in : out STD_LOGIC;
    updn_on_off : out STD_LOGIC;
    usb_uart_rxd : in STD_LOGIC;
    usb_uart_txd : out STD_LOGIC;
    vadj : out STD_LOGIC_VECTOR ( 2 downto 0 );
    voladj : in STD_LOGIC_VECTOR ( 2 downto 0 );
    xadc_data : in STD_LOGIC_VECTOR ( 15 downto 0 )
  );

end hdmi_wrapper;

architecture stub of hdmi_wrapper is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
begin
end;
