# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/AlienWare/Course/ECE532/MileStone7/Testing/Nexys4DDRXADC/Nexys-4-DDR-XADC/src/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Testing/Nexys4DDRXADC/Nexys-4-DDR-XADC/src/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Testing/Nexys4DDRXADC/Nexys-4-DDR-XADC/src/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Testing/Nexys4DDRXADC/Nexys-4-DDR-XADC/src/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Testing/Nexys4DDRXADC/Nexys-4-DDR-XADC/src/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Testing/Nexys4DDRXADC/Nexys-4-DDR-XADC/src/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
