# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/constraints/NexysVideo_Master.xdc

# Block Designs: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/hdmi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi || ORIG_REF_NAME==hdmi} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_dynclk_0_0/hdmi_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_axi_dynclk_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_gpio_video_0 || ORIG_REF_NAME==hdmi_axi_gpio_video_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_mem_intercon_0/hdmi_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_axi_mem_intercon_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_timer_0_0 || ORIG_REF_NAME==hdmi_axi_timer_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==hdmi_axi_uartlite_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_axi_vdma_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dvi2rgb_0_0/hdmi_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_dvi2rgb_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_mdm_1_0 || ORIG_REF_NAME==hdmi_mdm_1_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_0 || ORIG_REF_NAME==hdmi_microblaze_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hdmi_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_axi_periph_0/hdmi_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hdmi_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dlmb_bram_if_cntlr_0/hdmi_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dlmb_v10_0 || ORIG_REF_NAME==hdmi_dlmb_v10_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ilmb_bram_if_cntlr_0/hdmi_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_ilmb_v10_0 || ORIG_REF_NAME==hdmi_ilmb_v10_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_lmb_bram_0/hdmi_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_lmb_bram_0 || ORIG_REF_NAME==hdmi_lmb_bram_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_xlconcat_0/hdmi_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_xlconcat_0 || ORIG_REF_NAME==hdmi_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_mig_7series_0_0 || ORIG_REF_NAME==hdmi_mig_7series_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rgb2dvi_0_0/hdmi_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_rgb2dvi_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_pxl_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_pxl_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_tc_0_0 || ORIG_REF_NAME==hdmi_v_tc_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_tc_1_0 || ORIG_REF_NAME==hdmi_v_tc_1_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_xlconstant_0_0/hdmi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xlconstant_0_0 || ORIG_REF_NAME==hdmi_xlconstant_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xbar_1 || ORIG_REF_NAME==hdmi_xbar_1} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xbar_0 || ORIG_REF_NAME==hdmi_xbar_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_UDP_0_0/hdmi_UDP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_UDP_0_0 || ORIG_REF_NAME==hdmi_UDP_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_clk_0_0/hdmi_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_clk_0_0 || ORIG_REF_NAME==hdmi_clk_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_c_counter_binary_0_0/hdmi_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_c_counter_binary_0_0 || ORIG_REF_NAME==hdmi_c_counter_binary_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_c_counter_binary_1_0/hdmi_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_c_counter_binary_1_0 || ORIG_REF_NAME==hdmi_c_counter_binary_1_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_clk_wiz_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_control_0_0/hdmi_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_control_0_0 || ORIG_REF_NAME==hdmi_control_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dist_mem_gen_0_0/hdmi_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dist_mem_gen_0_0 || ORIG_REF_NAME==hdmi_dist_mem_gen_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_DAC_0_0/hdmi_DAC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_DAC_0_0 || ORIG_REF_NAME==hdmi_DAC_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ADC_fpga_d_0_0/hdmi_ADC_fpga_d_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_ADC_fpga_d_0_0 || ORIG_REF_NAME==hdmi_ADC_fpga_d_0_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ADC_fpga_d_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ADC_fpga_d_0_0/src/pixel_buffer/pixel_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pixel_buffer || ORIG_REF_NAME==pixel_buffer} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ADC_fpga_d_0_0/src/init_sequence_rom/init_sequence_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==init_sequence_rom || ORIG_REF_NAME==init_sequence_rom} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_FilterIIR_0_0/hdmi_FilterIIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_FilterIIR_0_0 || ORIG_REF_NAME==hdmi_FilterIIR_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ampDec_0_0/hdmi_ampDec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_ampDec_0_0 || ORIG_REF_NAME==hdmi_ampDec_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_PhaseDetector_0_0/hdmi_PhaseDetector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_PhaseDetector_0_0 || ORIG_REF_NAME==hdmi_PhaseDetector_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_vip_0_0/hdmi_axi_vip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_vip_0_0 || ORIG_REF_NAME==hdmi_axi_vip_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_interconnect_0_0/hdmi_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_interconnect_0_0 || ORIG_REF_NAME==hdmi_axi_interconnect_0_0} -quiet] -quiet

# IP: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_xbar_2/hdmi_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xbar_2 || ORIG_REF_NAME==hdmi_xbar_2} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_pc_0/hdmi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_pc_0 || ORIG_REF_NAME==hdmi_auto_pc_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_m00_regslice_0 || ORIG_REF_NAME==hdmi_m00_regslice_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_ds_0 || ORIG_REF_NAME==hdmi_auto_ds_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_rs_w_0 || ORIG_REF_NAME==hdmi_auto_rs_w_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s03_regslice_0 || ORIG_REF_NAME==hdmi_s03_regslice_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s02_regslice_0 || ORIG_REF_NAME==hdmi_s02_regslice_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s01_regslice_0 || ORIG_REF_NAME==hdmi_s01_regslice_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_us_1 || ORIG_REF_NAME==hdmi_auto_us_1} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_rs_w_2 || ORIG_REF_NAME==hdmi_auto_rs_w_2} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s00_regslice_0 || ORIG_REF_NAME==hdmi_s00_regslice_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_us_0 || ORIG_REF_NAME==hdmi_auto_us_0} -quiet] -quiet

# IP: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_rs_w_1 || ORIG_REF_NAME==hdmi_auto_rs_w_1} -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_gpio_video_0 || ORIG_REF_NAME==hdmi_axi_gpio_video_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_gpio_video_0 || ORIG_REF_NAME==hdmi_axi_gpio_video_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_timer_0_0 || ORIG_REF_NAME==hdmi_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==hdmi_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==hdmi_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_dvi2rgb_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_mdm_1_0 || ORIG_REF_NAME==hdmi_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0_ooc_trace.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_0 || ORIG_REF_NAME==hdmi_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0_ooc_debug.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hdmi_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hdmi_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dlmb_bram_if_cntlr_0/hdmi_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_dlmb_v10_0 || ORIG_REF_NAME==hdmi_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ilmb_bram_if_cntlr_0/hdmi_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_ilmb_v10_0 || ORIG_REF_NAME==hdmi_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_lmb_bram_0/hdmi_lmb_bram_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/constraints/hdmi_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_mig_7series_0_0 || ORIG_REF_NAME==hdmi_mig_7series_0_0} -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/constraints/hdmi_mig_7series_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_mig_7series_0_0 || ORIG_REF_NAME==hdmi_mig_7series_0_0} -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_pxl_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_pxl_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_pxl_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_pxl_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_v_tc_0_0 || ORIG_REF_NAME==hdmi_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_v_tc_1_0 || ORIG_REF_NAME==hdmi_v_tc_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_c_counter_binary_0_0/hdmi_c_counter_binary_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_c_counter_binary_1_0/hdmi_c_counter_binary_1_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_dist_mem_gen_0_0/hdmi_dist_mem_gen_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ADC_fpga_d_0_0/src/charLib/charLib_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ADC_fpga_d_0_0/src/pixel_buffer/pixel_buffer_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_ADC_fpga_d_0_0/src/init_sequence_rom/init_sequence_rom_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_axi_vip_0_0/hdmi_axi_vip_0_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_xbar_2/hdmi_xbar_2_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_pc_0/hdmi_auto_pc_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_auto_ds_0 || ORIG_REF_NAME==hdmi_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_auto_us_1 || ORIG_REF_NAME==hdmi_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_auto_us_0 || ORIG_REF_NAME==hdmi_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_ooc.xdc

# XDC: d:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1_ooc.xdc

# XDC: D:/AlienWare/Course/ECE532/MileStone7/Nexys-Video-HDMI/src/bd/hdmi/hdmi_ooc.xdc
