# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/jaimin/xilinxprojects/mengproject/ips/phasedetector/edit_phasedetector_v1_0.tmp/filteriir_v1_0_project/FilterIIR_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/jaimin/xilinxprojects/mengproject/ips/phasedetector/edit_phasedetector_v1_0.tmp/filteriir_v1_0_project/FilterIIR_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/PhaseDetector/PhaseDetector_1.0
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/DecimationFilter/DecimationFilter_1.0
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Control/ip_repo/Control_1.0
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Control/ip_repo/Control_1.0
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Clock_Gen/ip_repo/Clock_Gen_1.0
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/UDP/ip_repo/UDP_1.0
} [current_project]
set_property ip_output_repo c:/users/jaimin/xilinxprojects/mengproject/ips/phasedetector/edit_phasedetector_v1_0.tmp/filteriir_v1_0_project/FilterIIR_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/hdl/FilterIIR_v1_0_S00_AXI.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/src/delay.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/src/filter_iir.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/src/last_section.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/src/lowpass_section_sample.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/src/multiply.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/src/subtract.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/src/sum.v
  c:/Users/Jaimin/XilinxProjects/MEngProject/IPs/Filter_IIR/FilterIIR_1.0/hdl/FilterIIR_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top FilterIIR_v1_0 -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FilterIIR_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FilterIIR_v1_0_utilization_synth.rpt -pb FilterIIR_v1_0_utilization_synth.pb"
